<template>
  <div  class="ruleClause">
    <div v-if="$store.state.lanCode==1">
<p class="title">Chào mừng bạn đến sử dụng phần mềm "K188" và các dịch vụ liên quan!</p>
<p class="con">Phần mềm "K188" và các dịch vụ liên quan đề cập đến các ứng dụng khách được sở hữu và điều hành hợp pháp của công ty được đánh dấu là "K188 Media" và trang web của "K188 Media Network" (www.K188.vip) được cung cấp cho bạn các sản phẩm và dịch vụ, bao gồm nhưng không giới hạn đến các đề xuất được cá nhân hóa, phát hành thông tin, giao tiếp tương tác, truy vấn tìm kiếm và các chức năng cốt lõi khác, là các nền tảng để tạo và giao tiếp. Thỏa thuận với công ty về việc bạn đăng ký, đăng nhập, sử dụng (sau đây gọi chung là "sử dụng") phần mềm "K188" và các dịch vụ liên quan.</p>
      
<p class="con">Để cung cấp cho bạn các dịch vụ tốt hơn, vui lòng đọc kỹ và hiểu đầy đủ thỏa thuận này trước khi bạn bắt đầu sử dụng phần mềm "K188" và các dịch vụ liên quan, đặc biệt là các điều khoản liên quan đến miễn trừ hoặc giới hạn trách nhiệm pháp lý, cấp phép quyền và điều khoản sử dụng thông tin, đồng thời đồng ý điều khoản mở và sử dụng các dịch vụ cá nhân đặc biệt, luật hiện hành và điều khoản giải quyết tranh chấp, v.v. Trong số đó, những nội dung quan trọng như điều khoản miễn trừ hoặc giới hạn trách nhiệm pháp lý sẽ được nhắc nhở dưới dạng in đậm, và bạn nên đọc chúng một cách rõ ràng. Nếu bạn dưới 18 tuổi, vui lòng đọc và hiểu đầy đủ thỏa thuận này với người giám hộ hợp pháp của bạn, đồng thời sử dụng phần mềm "K188" và các dịch vụ liên quan sau khi được sự đồng ý của người giám hộ hợp pháp.</p>
<p class="con">Nếu bạn không đồng ý với thỏa thuận này, điều này sẽ dẫn đến việc chúng tôi không thể cung cấp cho bạn các sản phẩm và dịch vụ hoàn chỉnh và bạn cũng có thể chọn ngừng sử dụng nó. Nếu bạn tự nguyện chọn đồng ý hoặc sử dụng phần mềm "K188" và các dịch vụ liên quan, bạn nhận thấy rằng bạn đã hiểu đầy đủ về thỏa thuận này và đồng ý là một bên của thỏa thuận này để chấp nhận thỏa thuận này và các thỏa thuận và quy tắc khác liên quan đến "K188"phần mềm và các dịch vụ liên quan (Bao gồm nhưng không giới hạn ở" Chính sách độc quyền ").</p>

      <p class="title">Phần mềm "K188" và các dịch vụ liên quan</p>
      <p class="con">1. Khi bạn sử dụng phần mềm "K188" và các dịch vụ liên quan, bạn có thể tải ứng dụng khách "K188 Media" thông qua cài đặt trước, tải xuống từ bên thứ ba được công ty ủy quyền hoặc truy cập trang web liên quan của K188  Media ( www.K188.vip). Nếu bạn không nhận được phần mềm từ công ty hoặc bên thứ ba được công ty ủy quyền, công ty không thể đảm bảo rằng phiên bản không chính thức của phần mềm "K188" có thể được sử dụng bình thường và những tổn thất mà bạn phải gánh chịu do đó không liên quan gì với công ty.</p>
      <p class="con">2. Công ty có thể phát triển các phiên bản phần mềm ứng dụng khác nhau cho các thiết bị đầu cuối khác nhau. Bạn có thể lấy, tải xuống và cài đặt phiên bản phù hợp tùy theo điều kiện thực tế của thiết bị. Nếu bạn không còn sử dụng phần mềm "K188" và các dịch vụ liên quan, bạn cũng có thể tự gỡ cài đặt phần mềm ứng dụng tương ứng.</p>
      <p class="con">3. Để cải thiện trải nghiệm người dùng và dịch vụ tốt hơn, công ty sẽ cung cấp các bản cập nhật hoặc thay đổi đối với phần mềm "K188" và các dịch vụ liên quan theo thời gian (bao gồm nhưng không giới hạn ở việc sửa đổi, nâng cấp phần mềm, cải tiến chức năng, phát triển các dịch vụ mới, thay thế phần mềm, v.v.), Để đảm bảo an toàn cho phần mềm "K188" và các dịch vụ liên quan cũng như cải thiện dịch vụ người dùng, sau khi cập nhật một phần hoặc toàn bộ phần mềm "K188" và các dịch vụ liên quan, công ty sẽ sử dụng các phương pháp thích hợp (bao gồm nhưng không giới hạn đối với lời nhắc hệ thống, thông báo) khi khả thi, Thư trang web, v.v.) nhắc bạn rằng bạn có quyền chọn chấp nhận phiên bản cập nhật; nếu bạn chọn không cập nhật, một số chức năng của phần mềm "K188" và các dịch vụ liên quan sẽ bị hạn chế hoặc không thể sử dụng bình thường.</p>
      <p class="con">4. Trừ khi có sự cho phép trước bằng văn bản của công ty, phần mềm "K188" và các dịch vụ liên quan sẽ không được truy cập hoặc sử dụng dưới bất kỳ hình thức nào, bao gồm nhưng không phải để điều chỉnh danh mục, sao chép, phổ biến, tìm kiếm theo chiều dọc, thay thế hoặc giao dịch.</p>
      <p class="con">5. Bạn hiểu rằng để sử dụng phần mềm "K188" và các dịch vụ liên quan, bạn cần chuẩn bị thiết bị đầu cuối của riêng mình (như máy tính, điện thoại di động, v.v.) liên quan đến phần mềm và các dịch vụ liên quan. Sau khi bạn mở phần mềm "K188" trong thiết bị đầu cuối hoặc truy cập trang web "K188 Media." ", được coi là bạn sử dụng phần mềm" K188 "và các dịch vụ liên quan. Để thực hiện đầy đủ tất cả các chức năng của" K188  Media ", bạn có thể cần kết nối thiết bị đầu cuối Internet. Bạn hiểu rằng bạn sẽ chịu các chi phí bắt buộc (chẳng hạn như lưu lượng truy cập, phí Internet, v.v.).</p>
      <p class="con">6. Công ty cấp cho bạn quyền hợp pháp cá nhân, không thể chuyển nhượng, không độc quyền và phi thương mại để sử dụng phần mềm "K188" và các dịch vụ liên quan. Tất cả các quyền khác không được ủy quyền rõ ràng trong thỏa thuận này vẫn được bảo lưu bởi công ty. Bạn phải xin phép lại bằng văn bản của công ty trước khi thực hiện các quyền này. Đồng thời, việc công ty không thu hồi bất kỳ quyền nào không cấu thành việc từ bỏ quyền này .</p>
      <p class="con">7. Bạn có thể bắt đầu sử dụng phần mềm "K188" và các dịch vụ liên quan mà không cần đăng ký, nhưng một số chức năng hoặc dịch vụ có thể bị ảnh hưởng. Đồng thời, bạn cũng hiểu rằng, để cho phép bạn sử dụng tốt hơn phần mềm "K188" và các dịch vụ liên quan cũng như bảo vệ an ninh tài khoản của bạn, các chức năng nhất định và / hoặc các hạng mục dịch vụ riêng lẻ nhất định (chẳng hạn như dịch vụ đăng bình luận, v.v. ) sẽ yêu cầu bạn tuân theo Theo luật và quy định có liên quan của quốc gia, đăng ký tên thật và đăng nhập có thể được sử dụng sau khi cung cấp thông tin nhận dạng thực.</p>

      <p class="title">Giới thiệu về "Tài khoản"</p>
      <p class="con">1. Phần mềm "K188" và các dịch vụ liên quan cung cấp cho bạn kênh đăng ký, bạn có thể chọn tổ hợp ký tự hợp pháp làm tài khoản của mình, đồng thời đặt mật khẩu đáp ứng các yêu cầu bảo mật. Bằng chứng về việc sử dụng phần mềm "K188" và các dịch vụ liên quan.</p>
      <p class="con">2. Bạn hiểu và cam kết rằng tài khoản bạn thiết lập sẽ không vi phạm luật pháp và quy định quốc gia cũng như nội quy công ty có liên quan, đồng thời sẽ không thực hiện bất kỳ hành vi nào xâm phạm đến lợi ích quốc gia, làm tổn hại đến quyền hợp pháp của công dân khác hoặc làm tổn hại đến đạo đức và thuần phong xã hội , tên tài khoản, ảnh đại diện của bạn và Thông tin đăng ký như hồ sơ và thông tin cá nhân khác sẽ không chứa thông tin bất hợp pháp và có hại. Cái gọi là sự cho phép của người khác sẽ không được sử dụng dưới danh nghĩa của người khác (bao gồm nhưng không giới hạn ở việc sử dụng gian lận tên, tên, kích thước phông chữ, hình đại diện và các phương pháp khác bị nghi ngờ gây ra sự thay thế của người khác), và sẽ không độc hại Đăng ký tài khoản "K188 Media" (bao gồm nhưng không mở rộng đăng ký trước đó, đăng ký hàng loạt tài khoản, v.v.). Công ty có quyền xem xét thông tin bạn gửi.</p>
      <p class="con">3. Tài khoản của bạn được giới hạn cho mục đích sử dụng của riêng bạn, được gọi là sự đồng ý bằng văn bản của công ty và không được cho, mượn, thuê, chuyển nhượng, bán hoặc cho phép người khác sử dụng tài khoản dưới mọi hình thức. Không phải là người đăng ký ban đầu của tài khoản, để bảo vệ tính bảo mật của tài khoản, công ty có quyền tạm ngừng hoặc chấm dứt ngay lập tức việc cung cấp dịch vụ cho tài khoản đã đăng ký, hoặc thay thế tài khoản.</p>
      <p class="con">4. Bạn có trách nhiệm duy trì tính bảo mật và bí mật của tài khoản và mật khẩu cá nhân của bạn. Phần mềm K188 "và các dịch vụ liên quan Mọi trách nhiệm pháp lý có thể phát sinh từ các hoạt động như sửa đổi dữ liệu, xuất bản bình luận, thanh toán ngân sách, v.v. Trong trường hợp có tài khoản hoặc bất kỳ vi phạm bảo mật nào khác, bạn phải thông báo ngay cho công ty.</p>
      <p class="con">5. Trong trường hợp mất tài khoản hoặc quên mật khẩu, bạn có thể làm theo phương pháp của công ty để sửa và yêu cầu tài khoản hoặc mật khẩu một cách kịp thời. Bạn hiểu và đồng ý rằng cơ chế lấy lại mật khẩu của công ty chỉ cần xác định thông tin được điền trên cá nhân và dữ liệu ghi lại hệ thống. Hãy đặc biệt chú ý đến tài khoản và mật khẩu của bạn. Khi sử dụng xong, bạn nên thoát ra ngoài một cách an toàn. Nếu vì lý do riêng của bạn như quản lý không đúng cách hoặc các yếu tố bất khả kháng khác, bạn sẽ phải chịu trách nhiệm về hành vi trộm cắp tài khoản nghiêm trọng hoặc mất mật khẩu của bạn.</p>
      <p class="con">6. Khi đăng ký, sử dụng và quản lý tài khoản của mình, bạn nên đảm bảo tính xác thực của thông tin nhận dạng mà bạn đã điền khi đăng ký tài khoản. (Theo luật và quy định của quốc gia có liên quan, để sử dụng một số chức năng của phần mềm "K188" và các dịch vụ liên quan, bạn cần điền thông tin nhận dạng thực. Vui lòng làm theo hướng dẫn có liên quan. Hoàn tất xác thực tên thật theo pháp luật, và chú ý cập nhật kịp thời những thông tin liên quan nêu trên Thông tin.Nếu tài liệu hoặc thông tin bạn cung cấp không chuẩn hoặc không đáp ứng yêu cầu, công ty có quyền từ chối cung cấp cho bạn những chức năng liên quan, và bạn có thể không sử dụng được hoặc không sử dụng được phần mềm "K188" và các dịch vụ liên quan.</p>
      <p class="con">7. Ngoài việc tự đăng ký tài khoản "K188 Media", người dùng cũng có thể cho phép sử dụng các tài khoản người dùng phần mềm khác mà họ sở hữu hợp pháp, bao gồm nhưng không đăng ký công ty và / hoặc các công ty liên kết và người thứ ba đã đăng ký tên thật- tài khoản người dùng phần mềm của bên đăng nhập để sử dụng phần mềm "K188" Và các dịch vụ liên quan, ngoại trừ những dịch vụ bị hạn chế hoặc cấm bởi phần mềm hoặc nền tảng của bên thứ ba. Khi người dùng đăng nhập bằng tài khoản trước đó, anh ta phải đảm bảo rằng tài khoản tương ứng đã được đăng ký bằng tên thật và các điều khoản liên quan trong thỏa thuận này được áp dụng đồng thời.</p>
      <p class="con">8. Bạn hiểu và đồng ý rằng ngoài việc đăng nhập và sử dụng phần mềm "K188" và các dịch vụ liên quan, bạn cũng có thể sử dụng tài khoản "K188 Media" của mình để đăng nhập và sử dụng các phần mềm và dịch vụ khác do công ty và các chi nhánh của nó cung cấp. Khi bạn đăng nhập bằng tài khoản "K188 Media" và sử dụng dịch vụ tiếp tục, bạn sẽ bị ràng buộc bởi "Thỏa thuận người dùng" của nhà cung cấp thực tế của dịch vụ lặp lại và các điều khoản thỏa thuận khác.</p>
      <p class="con">9. Để cải thiện khả năng hiển thị nội dung và hiệu quả xuất bản của bạn, bạn đồng ý rằng tài khoản của bạn trên phần mềm / trang web này và tất cả nội dung được xuất bản bởi tài khoản tương ứng được ủy quyền cho phép công ty tự động xuất bản cho công ty và / hoặc các công ty liên kết với bạn Phần mềm và trang web khác. Các thao tác mà bạn xuất bản, sửa đổi hoặc xóa nội dung trên phần mềm / trang web này sẽ được đồng bộ hóa với phần mềm và trang web khác trong loạt bài trên. Các sản phẩm phần mềm và trang web khác do công ty vận hành (nếu có) sẽ tuân theo "Thỏa thuận người dùng" của phần mềm và trang web đó và các điều khoản thỏa thuận khác.</p>
      <p class="con">10. Sau khi bạn hoàn tất việc đăng ký tài khoản "K188 Media", đăng nhập và thực hiện xác minh danh tính hợp lý và cần thiết, bạn có thể duyệt và sửa đổi thông tin nhận dạng cá nhân do chính mình gửi bất kỳ lúc nào. Bạn hiểu và đồng ý rằng bạn không thể sửa đổi thông tin đăng ký ban đầu và thông tin xác minh khác được cung cấp trong quá trình đăng ký vì lý do bảo mật và nhận dạng (chẳng hạn như dịch vụ khôi phục và truy xuất tài khoản hoặc mật khẩu, v.v.). Bạn cũng có thể đăng ký tài khoản. Công ty sẽ hỗ trợ bạn xóa tài khoản sau khi hoàn thành danh tính cá nhân, tình trạng bảo mật, thông tin thiết bị và các trường hợp hợp lý khác và xác minh cần thiết, đồng thời xóa tất cả thông tin về tài khoản của bạn theo yêu cầu của bạn. Pháp luật và các quy định khác nhau.</p>
      <p class="con">11. Bạn hiểu và đồng ý rằng để sử dụng hết tài nguyên của tài khoản, công ty có quyền xóa tài khoản của bạn nếu bạn không đăng nhập lần đầu sau khi đăng ký hoặc sử dụng tài khoản mà không đăng nhập quá hai lần liên tiếp. tháng.</p>

      <p class="title">Bảo vệ thông tin cá nhân của người dùng</p>
      <p class="con">Công ty hợp tác với bạn để bảo vệ thông tin cá nhân của bạn (tức là thông tin có thể xác định người dùng một cách độc lập hoặc kết hợp với các thông tin khác). Bảo vệ thông tin cá nhân của người dùng là một trong những nguyên tắc cơ bản của công ty. Trong quá trình sử dụng phần mềm "K188" và các dịch vụ liên quan, bạn có thể cần cung cấp thông tin cá nhân của mình (bao gồm nhưng không giới hạn tên, số điện thoại, thông tin vị trí, v.v.), công ty phanh sẽ cung cấp cho bạn những dịch vụ tốt hơn và tương ứng hỗ trợ kỹ thuật. Công ty sẽ sử dụng công nghệ mã hóa, ẩn danh và các biện pháp kỹ thuật khác phù hợp với phần mềm "K188" và các dịch vụ liên quan, cũng như các biện pháp bảo mật khác để bảo vệ thông tin cá nhân của bạn.</p>

      <p class="title">Quy tắc ứng xử của người dùng</p>
      <p class="con">1. Hành vi của người dùng yêu cầu bạn phải chịu trách nhiệm chính xác về việc sử dụng phần mềm này và các dịch vụ liên quan. Trừ khi được pháp luật cho phép hoặc được sự cho phép trước bằng văn bản của công ty, việc bạn sử dụng phần mềm "K188" và các dịch vụ liên quan không được có các hành vi sau:</p>
      <p class="con">1.1 Sử dụng bất kỳ trình cắm, trình cắm thêm, hệ thống hoặc công cụ của bên thứ ba nào được công ty liên quan ủy quyền hoặc cấp phép để can thiệp, phá hủy, sửa đổi hoặc gây ảnh hưởng khác đến hoạt động bình thường của phần mềm "K188" và các dịch vụ liên quan.</p>
      <p class="con">1.2 Sử dụng hoặc nhắm mục tiêu phần mềm "K188" và các dịch vụ liên quan để thực hiện bất kỳ hành vi nào gây nguy hiểm cho an ninh mạng máy tính, bao gồm nhưng không giới hạn ở:</p>
      <p class="con">(1) Các hoạt động gây nguy hiểm cho an ninh mạng như xâm phạm trái phép mạng của người khác, can thiệp vào các chức năng bình thường của mạng của người khác và ăn cắp dữ liệu mạng;</p>
      <p class="con">(2) Cung cấp các chương trình và công cụ được sử dụng đặc biệt cho các mạng xâm nhập quân sự, can thiệp vào các chức năng mạng thông thường và các biện pháp bảo vệ, ăn cắp dữ liệu mạng và các hoạt động khác gây nguy hiểm cho an ninh mạng;</p>
      <p class="con">(3) Cung cấp hỗ trợ kỹ thuật, xúc tiến quảng cáo, thanh toán và hỗ trợ khác khi biết rằng quân đội dân sự đang gây nguy hiểm cho các hoạt động an ninh mạng;</p>
      <p class="con">(4) Sử dụng dữ liệu được cơ quan có thẩm quyền cho phép hoặc máy chủ / tài khoản được cơ quan truy cập cho phép;</p>
      <p class="con">(5) Cho phép truy cập vào các mạng máy tính công cộng hoặc các hệ thống máy tính khác và xóa, sửa đổi hoặc thêm thông tin được lưu trữ;</p>
      <p class="con">(6) Cho phép, cố gắng phát hiện, quét, kiểm tra các điểm yếu của hệ thống hoặc mạng "K188 Media" hoặc thực hiện các hành vi khác phá hoại an ninh mạng;</p>
      <p class="con">(7) Cố gắng can thiệp, làm gián đoạn hoạt động bình thường của hệ thống hoặc trang web "K188 Media", phát tán các chương trình hoặc vi rút độc hại và các hành vi khác làm gián đoạn, gây nhiễu cho các dịch vụ thông tin mạng thông thường;</p>
      <p class="con">(8) Tên gói dữ liệu TCP / IP giả mạo hoặc một phần của tên;</p>
      <p class="con">(9) Kỹ sư đảo ngược, biên dịch ngược, biên dịch hoặc cố gắng khám phá mã nguồn của phần mềm này cho phần mềm "K188" và các dịch vụ liên quan;</p>
      <p class="con">(10) Đăng ký tài khoản độc hại cho phần mềm "K188" và các dịch vụ liên quan, bao gồm nhưng không mở rộng việc lặp lại, đăng ký hàng loạt tài khoản;</p>
      <p class="con">(11) Vi phạm pháp luật và các quy định, thỏa thuận này, nội quy công ty có liên quan và các hành vi khác vi phạm quyền hợp pháp của người khác.</p>
      <p class="con">1.3 Nếu công ty có lý do để tin rằng hành vi của bạn vi phạm hoặc có thể vi phạm thỏa thuận trên, công ty có thể độc lập đưa ra phán quyết và giải quyết, đồng thời có quyền chấm dứt việc cung cấp dịch vụ cho bạn mà không cần thông báo trước và theo đuổi pháp luật có liên quan nợ phải trả.</p>
      <p class="con">2. Đặc tả nội dung thông tin</p>
      <p class="con">2.1 Sau khi hoàn tất xác thực tên thật theo quy định, bạn có thể đăng nhập vào "K188 Media" bằng tài khoản đã đăng ký hoặc tài khoản nền tảng hợp tác "K188 Media" để đăng nội dung, đăng bình luận, v.v.</p>
      <p class="con">2.2 Công ty cam kết làm cho việc phát hành thông tin và đăng bình luận là một sự trao đổi ý kiến ​​văn minh, hợp lý, thân thiện và thay thế. Trong khi thúc đẩy sự phát triển của phát hành thông tin, truyền thông tương tác và phát triển kinh doanh bài viết bình luận, chúng tôi sẽ tiếp tục tăng cường khả năng quản lý an toàn thông tin tương ứng, cải thiện việc phát hành thông tin, đăng và bình luận tự giác, nghiêm túc thực hiện trách nhiệm xã hội, tuân thủ quốc gia pháp luật và các quy định, tôn trọng quyền và lợi ích hợp pháp của công dân, tôn trọng trật tự công cộng xã hội và thuần phong mỹ tục.</p>
      <p class="con">2.3. và tính xác thực của thông tin. Tạo, sao chép, xuất bản và phổ biến nội dung thông tin sau đây bị cấm bởi luật và quy định:</p>
      <p class="con">(1) Phản đối các nguyên tắc cơ bản do Hiến pháp thiết lập;</p>
      <p class="con">(2) Gây nguy hiểm đến an ninh quốc gia và chuyển tiếp bí mật nhà nước;</p>
      <p class="con">(3) Lật đổ quyền lực nhà nước, lật đổ hệ thống xã hội chủ nghĩa, kích động chia rẽ đất nước, phá hoại đoàn kết dân tộc;</p>
      <p class="con">(4) Thiệt hại đến danh dự và lợi ích quốc gia;</p>
      <p class="con">(5) Thúc đẩy chủ nghĩa khủng bố và chủ nghĩa cực đoan;</p>
      <p class="con">(6) Tuyên truyền hận thù dân tộc, kỳ thị dân tộc, phá hoại đoàn kết dân tộc;</p>
      <p class="con">(7) Kích động phân biệt đối xử hoặc thù hận trong khu vực;</p>
      <p class="con">(8) Phá hoại chính sách tôn giáo của nhà nước và cổ vũ các tín ngưỡng, mê tín dị đoan;</p>
      <p class="con">(9) Bịa đặt, tung tin đồn thất thiệt, gây rối trật tự kinh tế, trật tự xã hội, phá hoại ổn định xã hội;</p>
      <p class="con">(10) Truyền bá, phổ biến bạo lực, tục tĩu, khiêu dâm, lừa đảo, giết người, khủng bố hoặc xúi giục tội phạm;</p>
      <p class="con">(11) Xâm phạm quyền và lợi ích hợp pháp của người chưa thành niên hoặc xâm hại đến sức khỏe con người của người chưa thành niên;</p>
      <p class="con">(12) Không được phép của chủ sở hữu, bí mật chụp ảnh, quay lén người khác, xâm phạm quyền lợi hợp pháp của người khác;</p>
      <p class="con">(13) Chứa nội dung khủng khiếp, bạo lực, đẫm máu, rất nguy hiểm và gây nguy hiểm cho sức khỏe của người biểu diễn hoặc những người khác;</p>
      <p class="con">(14) Gây nguy hiểm cho an ninh mạng, sử dụng quân sự mạng gây nguy hiểm cho an ninh, danh dự và lợi ích quốc gia;</p>
      <p class="con">(15) Xúc phạm, báng bổ người khác, xâm phạm quyền và lợi ích hợp pháp của người khác;</p>
      <p class="con">(16) Đe dọa, đe dọa bằng bạo lực và tìm kiếm xác thịt người chống lại người khác;</p>
      <p class="con">(17) Liên quan đến quyền riêng tư dân sự, thông tin cá nhân hoặc dữ liệu;</p>
      <p class="con">(18) Truyền bá ngôn từ xấu xa, gây tổn hại đến trật tự công cộng và thuần phong mỹ tục;</p>
      <p class="con">(19) Xâm phạm quyền và lợi ích hợp pháp của người khác như độc quyền, quyền danh tiếng, quyền chân dung, quyền sở hữu trí tuệ, v.v.;</p>
      <p class="con">(20) Truyền bá các quảng cáo thương mại, hoặc thông tin chào mời thương mại tương tự, thông tin tiếp thị quá mức và thư rác;</p>
      <p class="con">(21) Nhận xét bằng các ngôn ngữ khác với các ngôn ngữ được sử dụng phổ biến trên trang web này;</p>
      <p class="con">(22) Không liên quan gì đến thông tin được bình luận;</p>23) Thông tin được công bố là vô nghĩa, hoặc cố tình sử dụng kết hợp các ký tự để tránh đánh giá kỹ thuật;
      <p class="con">(23) Thông tin được công bố là vô nghĩa, hoặc cố tình sử dụng kết hợp các ký tự để tránh đánh giá kỹ thuật;</p>
      <p class="con">(24) Thông tin khác vi phạm luật, quy định, chính sách, trật tự công cộng và thuần phong mỹ tục, gây cản trở hoạt động bình thường của "K188 Media" hoặc vi phạm quyền và lợi ích hợp pháp của người dùng khác hoặc bên thứ ba.</p>
      <p class="con">3. Công ty đã thiết lập nền tảng báo cáo và khiếu nại công khai. Bạn có thể khiếu nại với công ty theo hệ thống báo cáo và khiếu nại công khai của công ty, báo cáo các hành vi vi phạm pháp luật và quy định đã phân loại, các hoạt động truyền thông bất hợp pháp, thông tin bất hợp pháp và có hại, v.v. công ty sẽ nhanh chóng truy tố và xử lý các khiếu nại và báo cáo của bạn, Để cùng nhau tạo ra một không gian mạng trong sạch và ngay thẳng.</p>

      <p class="title">Thông số kỹ thuật sử dụng nội dung thông tin của "K188 Media"</p>
      <p class="con">1. Nếu không có sự cho phép bằng văn bản của công ty, bạn không được cung cấp hoặc hỗ trợ bất kỳ bên thứ ba nào thực hiện các hành động sau đối với nội dung thông tin của phần mềm "K188" và các dịch vụ liên quan trong thỏa thuận này:</p>
      <p class="con">(1) Sao chép, đọc và sử dụng nội dung thông tin của phần mềm "K188" và các dịch vụ liên quan, bao gồm nhưng không giới hạn mục đích thương mại như quảng cáo, tăng lượng đọc và lượng duyệt;</p>
      <p class="con">(2) Chỉnh sửa, phân loại và sắp xếp trái phép nội dung thông tin của phần mềm "K188" và các dịch vụ liên quan, sau đó hiển thị chúng trên các kênh khác ngoài trang nguồn của phần mềm "K188" và các dịch vụ liên quan;</p>
      <p class="con">(3) Áp dụng bất kỳ hình thức phương pháp nhận dạng nào, bao gồm nhưng không xác định trước các dấu đặc biệt, mã đặc biệt, v.v., để tạo lưu lượng truy cập vào nội dung thông tin của phần mềm "K188" và các dịch vụ liên quan của chính mình hoặc hỗ trợ bên thứ ba, dẫn đầu đến khối lượng đọc, chuyển, chiếm quyền điều khiển, v.v. Ảnh hưởng;</p>
      <p class="con">(4) Các hành vi khác nhằm lấy hoặc sử dụng trái phép nội dung thông tin của phần mềm "K188" và các dịch vụ liên quan.</p>
      <p class="con">2. Với sự cho phép bằng văn bản của công ty, việc bạn chia sẻ và chuyển tiếp nội dung thông tin của phần mềm "K188" và các dịch vụ liên quan cũng phải tuân theo các thông số kỹ thuật sau:</p>
      <p class="con">(1) Để thu thập thông tin, thống kê và dữ liệu liên quan liên quan đến các từ phổ biến trong tìm kiếm, tỷ lệ truy cập, phân loại, lượng tìm kiếm, tỷ lệ nhấp, lượng đọc, v.v., công ty đồng ý trước bằng văn bản rằng dữ liệu nêu trên sẽ không được công khai hoặc cung cấp dưới bất kỳ hình thức nào, Cho phép với bất kỳ người thứ ba nào;</p>
      <p class="con">(2) Không đặt bất kỳ hình thức trang web nguồn nào của phần mềm "K188" và các dịch vụ liên quan, bao gồm nhưng không giới hạn các liên kết đến trang chủ (trang tệp cấu hình) của phần mềm "K188" và các dịch vụ liên quan, liên kết đến hệ thống quảng cáo, v.v. , hoặc Thực hiện bất kỳ hình thức chèn, chèn, bật lên, v.v. để chặn hiển thị trang nguồn của phần mềm "K188" và các dịch vụ liên quan;</p>
      <p class="con">(3) Thực hiện các biện pháp an toàn, hiệu quả và nghiêm ngặt thích hợp để ngăn chặn nội dung thông tin của phần mềm "K188" và các dịch vụ liên quan bị các bên thứ ba thu thập bất hợp pháp thông qua bất kỳ hình thức nào, bao gồm nhưng không giới hạn ở các chương trình "spider";</p>
      <p class="con">(4) Không được phép sử dụng nội dung dữ liệu có liên quan cho các mục đích ngoài phạm vi cho phép bằng văn bản của công ty cho bất kỳ hình thức bán hàng và sử dụng thương mại nào, hoặc tham gia, cung cấp hoặc cho phép bên thứ ba sử dụng dưới bất kỳ hình thức nào;</p>
      <p class="con">(5) Hành động chia sẻ, chuyển tiếp hoặc sao chép nội dung thông tin của phần mềm "K188" và các dịch vụ liên quan cho bất kỳ bên thứ ba nào sẽ tuân theo các thông số kỹ thuật và tiêu chuẩn khác do công ty thiết lập.</p>

      <p class="title">Vi phạm hợp đồng</p>
      <p class="con">1. Trước việc bạn vi phạm thỏa thuận này hoặc các điều khoản dịch vụ khác, công ty có quyền phán xét độc lập và đưa ra cảnh báo trước tùy theo tình huống, từ chối xuất bản, ngừng ngay việc truyền thông tin, xóa bài, rút ​​gọn. - cấm thay thế thời hạn và hạn chế một phần hoặc tất cả các chức năng của tài khoản cho đến khi các hồ sơ liên quan vĩnh viễn sẽ được lưu giữ về hành vi vi phạm pháp luật và quy định của nghi phạm và tội phạm bị nghi ngờ, và họ sẽ được báo cáo cho các cơ quan có liên quan theo quy định của pháp luật hợp tác với các cơ quan có liên quan trong cuộc điều tra của họ.</p>
      <p class="con">2. Nếu bạn vi phạm thỏa thuận này hoặc các điều khoản dịch vụ khác và gây ra khiếu nại hoặc kiện tụng của bên thứ ba, bạn nên tự xử lý và chịu mọi trách nhiệm pháp lý có thể xảy ra. Nếu sự vi phạm, vi phạm hoặc vi phạm hợp đồng của bạn khiến công ty và các chi nhánh của nó phải bồi thường cho bất kỳ bên thứ ba nào hoặc tuân theo các cơ quan nhà nước, bạn cũng phải bồi thường đầy đủ cho công ty và các chi nhánh của nó về mọi tổn thất do hậu quả gây ra.</p>
      <p class="con">3. Công ty tôn trọng và bảo vệ các quyền sở hữu trí tuệ, quyền danh tiếng, quyền tên, quyền sở hữu và các quyền hợp pháp khác của người dùng và những người khác. Bạn đảm bảo rằng văn bản, hình ảnh, video, âm thanh, liên kết, v.v. được tải lên khi sử dụng phần mềm "K188" và các dịch vụ liên quan không vi phạm bất kỳ quyền sở hữu trí tuệ, quyền danh tiếng, quyền tên, quyền sở hữu và các quyền khác và hợp pháp của bên thứ ba các quyền. Nếu không, công ty có quyền xóa nội dung bị cáo buộc vi phạm khi nhận được thông báo từ bên phải hoặc các bên liên quan. Đối với tất cả các khiếu nại của bên thứ ba, bạn nên xử lý và chịu mọi trách nhiệm pháp lý có thể có; nếu hành vi sở hữu của bạn khiến công ty và các chi nhánh của nó bị thiệt hại (bao gồm thiệt hại về kinh tế, thiện chí, v.v.), bạn vẫn nên Công ty và các chi nhánh của nó sẽ được bồi thường đầy đủ cho tất cả các tổn thất tuân theo.</p>

      <p class="title">Dịch vụ thay đổi, gián đoạn và chấm dứt</p>
      <p class="con">1. Bạn hiểu và đồng ý rằng phần mềm "K188" và các dịch vụ liên quan do công ty cung cấp được cung cấp phù hợp với hiện trạng có thể đạt được với công nghệ và điều kiện hiện có. Công ty sẽ cố gắng hết sức để cung cấp cho bạn các dịch vụ nhằm đảm bảo tính liên tục và an toàn của các dịch vụ. Bạn hiểu rằng công ty không thể thấy trước và ngăn ngừa các rủi ro kỹ thuật và các rủi ro khác bất cứ lúc nào, bao gồm nhưng không dần dần bất khả kháng, lý do mạng, lỗi dịch vụ của bên thứ ba, trang web của bên thứ ba và các lý do khác có thể gây gián đoạn dịch vụ, không sử dụng được phần mềm và dịch vụ bình thường, và các tổn thất và rủi ro khác.</p>
      <p class="con">2. Bạn hiểu và đồng ý rằng công ty có quyền xác định cài đặt dịch vụ / chức năng, phạm vi, sửa đổi, gián đoạn, tạm ngừng hoặc chấm dứt phần mềm "K188" và các dịch vụ liên quan để phục vụ hoạt động tổng thể và nhu cầu bảo mật hoạt động nền tảng .</p>

      <p class="title">Quảng cáo</p>
      <p class="con">1. Bạn hiểu và đồng ý rằng trong quá trình sử dụng phần mềm "K188" và các dịch vụ liên quan, công ty có thể quảng bá thông tin liên quan, dịch vụ quảng cáo hoặc quảng bá thương hiệu cho bạn, và công ty sẽ hiển thị trong phần mềm "K188" và các dịch vụ liên quan đến thương mại. quảng cáo, khuyến mãi hoặc thông tin (bao gồm thông tin thương mại hoặc phi thương mại) liên quan đến phần mềm "K188" và các dịch vụ liên quan và / hoặc các nhà cung cấp và đối tác bên thứ ba.</p>
      <p class="con">2. Khi sử dụng "K188 Media", công ty sẽ đẩy quảng cáo có lập trình cho bạn dựa trên mức độ ưu tiên, sở thích, v.v. Bạn có thể tắt tính năng đẩy quảng cáo có lập trình trong cài đặt "K188 Media". Nếu bạn tắt, số quảng cáo bạn nhìn thấy Sẽ vẫn như cũ, nhưng mức độ liên quan của quảng cáo sẽ giảm xuống.</p>
      <p class="con">3. Theo các nghĩa vụ liên quan đến quảng cáo và khuyến mại của công ty, bạn phải xác định tính xác thực và độ tin cậy của thông tin quảng cáo hoặc khuyến mại và tự chịu trách nhiệm về nhận định của mình. Ngoại trừ các quy định của pháp luật và quy định, việc mua bán, giao dịch của bạn do quảng cáo hoặc thông tin khuyến mãi hoặc thiệt hại hoặc mất mát do nghi ngờ vi phạm nội dung sẽ do bạn chịu và công ty sẽ không chịu trách nhiệm.</p>

      <p class="title">sở hữu trí tuệ</p>
      <p class="con">1. Việc mã hóa nội dung do công ty cung cấp trong phần mềm "K188" và các dịch vụ liên quan (bao gồm nhưng không giới hạn ở phần mềm, công nghệ, chương trình, trang web, văn bản, tranh, ảnh, âm thanh, video, biểu đồ, bố cục, điện tử tài liệu, v.v.) thuộc sở hữu của Công ty. Bản quyền, quyền bằng sáng chế và các quyền sở hữu trí tuệ khác của phần mềm mà công ty cung cấp dịch vụ này thuộc về công ty. Giám sát thiết bị, sao chép, phổ biến, hiển thị, hợp nhất, tải lên, tải xuống) phần mềm "K188" và các dịch vụ liên quan.</p>
      <p class="con">2. Bạn hiểu và đồng ý rằng văn bản, hình ảnh, video, âm thanh, v.v. được đăng và tải lên khi sử dụng phần mềm "K188" và các dịch vụ liên quan đều là bản gốc hoặc do bạn cho phép. Bản quyền của bất kỳ nội dung nào bạn tải lên thông qua "K188 Media" thuộc về bạn hoặc chủ sở hữu bản quyền ban đầu.</p>
      <p class="con">3. Bạn biết, hiểu và đồng ý rằng, để tiếp tục cải thiện và cung cấp cho bạn các dịch vụ tốt hơn, bạn tải lên, xuất bản, truyền hoặc phổ biến nội dung (bao gồm nhưng không giới hạn ở văn bản, hình ảnh, hình ảnh, âm thanh, v.v.) thông qua phần mềm "K188" và các dịch vụ liên quan, Âm nhạc, âm thanh, hội thoại, v.v. trong video và / hoặc âm thanh), các công ty được ủy quyền và các chi nhánh của họ, các công ty kiểm soát và kế thừa toàn cầu, miễn phí, không độc quyền, có thể cấp phép lại tương ứng của công ty (thông qua nhiều cấp độ) quyền (Bao gồm nhưng không phải quyền sao chép trước, quyền phổ biến mạng thông tin, quyền chuyển thể, quyền biên soạn, quyền sửa đổi, quyền dịch thuật, các dẫn xuất sản xuất, quyền biểu diễn và hiển thị), phạm vi sử dụng bao gồm nhưng không giới hạn ở hiện tại hoặc các trang web, ứng dụng, Sản phẩm hoặc thiết bị đầu cuối khác, v.v. Sau đó, bạn xác nhận và đồng ý rằng việc cấp các quyền trên được bao gồm trong nội dung, "K188 Media" / "K188 Media Network", bất kỳ công khai, khuyến mãi, quảng cáo và / hoặc liên quan đến công ty và / hoặc thương hiệu công ty, và / hoặc để tránh nhầm lẫn, Bạn đồng ý rằng việc ủy ​​quyền các quyền trên bao gồm việc cho phép sử dụng, sao chép, hiển thị, phổ biến hình ảnh cá nhân, chân dung, tên, nhãn hiệu, nhãn hiệu dịch vụ, nhãn hiệu, tên, biểu tượng, nhãn hiệu công ty và những thứ khác mà bạn sở hữu hoặc được phép sử dụng và nhúng vào nội dung.</p>
      <p class="con">4. Bạn xác nhận và đồng ý ủy quyền cho công ty dưới danh nghĩa của mình hoặc ủy thác cho một bên thứ ba chuyên nghiệp xâm phạm bản quyền của nội dung tải lên và phát hành của bạn, hoặc phân xử, hòa giải, dàn xếp, v.v. Công ty có quyền đưa ra quyết định về quyền quyết định bảo vệ và thực hiện chúng một cách độc lập.</p>
      <p class="con">5. Công ty cung cấp hỗ trợ kỹ thuật cho việc phát triển và vận hành "K188 Media", đồng thời chuyển đổi tất cả dữ liệu và thông tin được tạo ra trong quá trình phát triển và vận hành phần mềm "K188" và các dịch vụ liên quan sang tất cả các quyền trong phạm vi được luật bản quyền cho phép và các quy định.</p>
      <p class="con">6. Trong bất kỳ trường hợp nào, vui lòng không sử dụng công ty một cách riêng tư, bao gồm nhưng không giới hạn ở "K188", "K188 Media", "K188 Media Number", "K188 Media Network" và "www.K188.vip". công ty, với sự đồng ý trước bằng văn bản, bạn sẽ không hiển thị, sử dụng hoặc nộp đơn đăng ký nhãn hiệu, đăng ký tên miền, v.v., thay cho biểu tượng trong điều khoản này một mình hoặc trong bất kỳ sự kết hợp nào, và bạn sẽ không thực hiện các quyền rõ ràng hoặc ngụ ý đối với hiển thị, sử dụng, hoặc các quyền khác đối với người khác Hành động xử lý các dấu hiệu này. Do bạn vi phạm thỏa thuận này và việc sử dụng các nhãn hiệu, biểu tượng, v.v. nêu trên của công ty cho công ty hoặc những người khác gây thiệt hại, bạn sẽ chịu mọi trách nhiệm pháp lý.</p>

      <p class="title">Tuyên bố từ chối trách nhiệm</p>
      <p class="con">1. Bạn hiểu và đồng ý rằng phần mềm "K188" và các dịch vụ liên quan có thể bị ảnh hưởng hoặc bị can thiệp bởi nhiều yếu tố và công ty không đảm bảo (bao gồm nhưng không giới hạn):</p>
      <p class="con">1.1 Phần mềm "K188" và các dịch vụ liên quan hoàn toàn phù hợp với mọi yêu cầu của người dùng;</p>
      <p class="con">1.2 Phần mềm "K188" và các dịch vụ liên quan không bị xáo trộn, kịp thời, an toàn, đáng tin cậy hoặc không có bất kỳ lỗi nào; bất kỳ phần mềm, dịch vụ hoặc tài liệu nào khác mà bạn có được thông qua công ty đều đáp ứng được mong đợi của người dùng;</p>
      <p class="con">1.3 Bất kỳ lỗi nào trong phần mềm "K188" và các dịch vụ liên quan sẽ được sửa chữa.</p>
      <p class="con">2. Nếu bạn nghi ngờ có hành vi mượn hoặc thông tin tài sản trực tuyến, mật khẩu tài khoản, quảng cáo hoặc thông tin khuyến mãi bị nghi ngờ khác, vui lòng xử lý nó một cách thận trọng và đưa ra đánh giá của riêng bạn. thông tin vô hình Đối với tổn thất, công ty không chịu bất kỳ trách nhiệm bồi thường trực tiếp, gián tiếp, ngẫu nhiên, đặc biệt, phái sinh hoặc trừng phạt nào.</p>
      <p class="con">3. Bạn hiểu và đồng ý rằng trong quá trình sử dụng phần mềm "K188" và các dịch vụ liên quan, bạn có thể gặp phải các yếu tố bất khả kháng (bất khả kháng là những sự kiện khách quan không thể lường trước, không thể khắc phục và không thể tránh khỏi), bao gồm nhưng không hạn chế đối với thiên tai (như lũ lụt, động đất, bão, v.v.), hành động của chính phủ, chiến tranh, đình công, bạo loạn, bạo loạn, v.v. Trong trường hợp bất khả kháng, công ty sẽ cố gắng sửa chữa kịp thời nhưng công ty sẽ được miễn trách nhiệm trong phạm vi pháp luật và các quy định của pháp luật đối với những tổn thất do nguyên nhân bất khả kháng.</p>
      <p class="con">4. Công ty có quyền xử lý nội dung bất hợp pháp theo thỏa thuận này. Quyền này không cấu thành nghĩa vụ hoặc lời hứa của công ty và công ty không thể đảm bảo rằng các hoạt động bất hợp pháp sẽ được phát hiện kịp thời hoặc bị xử lý cho phù hợp.</p>
      <p class="con">5. Bạn hiểu và đồng ý rằng công ty không cung cấp bất kỳ loại đảm bảo hoặc điều kiện rõ ràng hoặc ngụ ý nào liên quan đến phần mềm "K188" và các dịch vụ liên quan, bao gồm nhưng không giới hạn ở khả năng tiếp thị thương mại, khả năng áp dụng cho các mục đích cụ thể, v.v. Và việc sử dụng các dịch vụ liên quan là rủi ro của riêng bạn. </p>
      <p class="con">6. Bạn hiểu và đồng ý rằng thỏa thuận này là tuân thủ luật pháp và quy định quốc gia, duy trì trật tự công cộng và thuần phong mỹ tục, bảo vệ quyền và lợi ích hợp pháp của người khác. quy định trong phạm vi khả năng của mình nhưng không đảm bảo rằng bản án của công ty hoàn toàn phù hợp với cơ quan xét xử., bản án của cơ quan hành chính là nhất quán, nếu hậu quả phát sinh do đó bạn tự hiểu và đồng ý gánh chịu.</p>
      <p class="con">7. Trong mọi trường hợp, công ty sẽ không chịu trách nhiệm đối với bất kỳ thiệt hại gián tiếp, do hậu quả, trừng phạt, ngẫu nhiên, đặc biệt hoặc hình phạt, bao gồm cả việc mất lợi nhuận mà bạn phải chịu khi sử dụng phần mềm "K188" và các dịch vụ liên quan. Toàn bộ trách nhiệm của công ty đối với bạn, bất kể lý do hay hành vi danh nghĩa, sẽ không bao giờ vượt quá chi phí (nếu có) mà bạn đã trả cho công ty để sử dụng phần mềm "K188" và các dịch vụ liên quan trong cơ quan của thành viên.</p>

      <p class="title">Thỏa thuận đặc biệt về các dịch vụ cá nhân và dịch vụ của bên thứ ba</p>
      <p class="con">1. Phần mềm "K188" và các dịch vụ liên quan bao gồm các phương pháp pháp lý khác nhau của công ty để lấy thông tin hoặc liên kết nội dung thông tin, cũng như các dịch vụ cá nhân khác được điều hành hợp pháp bởi công ty và / hoặc các bên liên quan. Bạn có thể mở và sử dụng các dịch vụ riêng lẻ trên trong phần mềm "K188". Một số dịch vụ riêng lẻ nhất định có thể yêu cầu bạn chấp nhận đồng thời thỏa thuận được sắp xếp cụ thể cho điều này hoặc các quy tắc khác hạn chế bạn và nhà cung cấp dịch vụ cá nhân, đồng thời cung cấp cho bạn những thỏa thuận này một cách dễ thấy khi bạn dự định sử dụng dịch vụ một chiều khi cần thiết., Quy tắc, để bạn tham khảo và đồng ý. Khi bạn bắt đầu sử dụng các dịch vụ trên, có nghĩa là bạn đã hiểu và chấp nhận các thỏa thuận và quy tắc có liên quan điều chỉnh các dịch vụ riêng lẻ. Nếu thời hạn sử dụng không được chỉ định, hoặc thời hạn sử dụng không được chỉ định là "vĩnh viễn", "vô thời hạn" hoặc "không giới hạn", thì thời hạn sử dụng của các sản phẩm hoặc dịch vụ này là kể từ khi người dùng bắt đầu sử dụng sản phẩm hoặc dịch vụ cho đến khi sản phẩm hoặc dịch vụ được sử dụng. Cho đến ngày phần mềm "K188" chuyển sang chế độ ngoại tuyến.</p>
      <p class="con">2. Nếu bạn sử dụng phần mềm hoặc các dịch vụ liên quan do bên thứ ba cung cấp trong phần mềm "K188", ngoài việc tuân thủ thỏa thuận này và các quy tắc liên quan của K188  Media, bạn cũng có thể cần phải đồng ý và tuân theo thỏa thuận của bên thứ ba, chính sách độc quyền và các quy tắc liên quan. Các tranh chấp, tổn thất hoặc thiệt hại phát sinh từ phần mềm của bên thứ ba và các dịch vụ liên quan sẽ do bạn và bên thứ ba giải quyết. Công ty không chịu bất kỳ trách nhiệm nào với bạn hoặc bất kỳ bên thứ ba nào về việc này.</p>

      <p class="title">Điều khoản sử dụng cho trẻ vị thành niên</p>
      <p class="con">1. Nếu người dùng là trẻ vị thành niên dưới 18 tuổi nên đọc kỹ thỏa thuận này dưới sự giám hộ, hướng dẫn và đồng ý của người giám hộ trước khi sử dụng phần mềm "K188" và các dịch vụ liên quan.</p>
      <p class="con">2. Công ty bảo vệ thông tin cá nhân của trẻ vị thành niên. Khi điền thông tin cá nhân, người dùng chưa đủ tuổi nên nâng cao nhận thức về bảo vệ cá nhân và thực hiện các biện pháp thích hợp, sử dụng đúng phần mềm "K188" và các dịch vụ liên quan khi được người giám hộ hướng dẫn.</p>
      <p class="con">3. Người dùng chưa thành niên hiểu rằng nếu bạn vi phạm pháp luật và các quy định và nội dung của thỏa thuận này, bạn và người giám hộ của bạn phải tuân theo pháp luật và chịu mọi trách nhiệm pháp lý có thể phát sinh.</p>
      <p class="con">4. Nhắc nhở đặc biệt cho người dùng nhỏ tuổi:</p>
      <p class="con">4.1 Thanh thiếu niên sử dụng phần mềm này và các dịch vụ liên quan nên học cách sử dụng Internet đúng cách trong phạm vi hợp lý dưới sự giám sát và hướng dẫn của người giám hộ, tránh tham gia vào không gian ảo và phát triển thói quen sử dụng Internet tốt.</p>
      <p class="con">4.2 Người dùng trẻ phải tuân thủ "Công ước Văn minh Mạng Thanh niên Quốc gia":</p>
      <p class="con">(1) Học hỏi trực tuyến tốt và không duyệt thông tin xấu;</p>
      <p class="con">(2) Giao tiếp trung thực, thân thiện, không xúc phạm hoặc lừa dối người khác;</p>
      <p class="con">(3) Nâng cao nhận thức tự chăm sóc bản thân và không hẹn hò với bạn bè theo ý muốn;</p>
      <p class="con">(4) Cần duy trì an ninh mạng và không phá hủy cấp độ mạng;</p>
      <p class="con">(5) Tốt cho sức khỏe thể chất và tinh thần, không mê đắm thời gian và không gian ảo.</p>
      <p class="con">5. Để bảo vệ quyền lợi của trẻ vị thành niên tốt hơn, công ty nhắc nhở người dùng cẩn thận xuất bản nội dung có chứa tài liệu nhỏ. . của trẻ vị thành niên. Và cho phép công ty sử dụng và xử lý các nội dung liên quan đến trẻ vị thành niên này theo thỏa thuận này.</p>

      <p class="title">khác</p>
      <p class="con">1. Việc xác lập, có hiệu lực, ký kết, giải thích và giải quyết các tranh chấp của hiệp định này sẽ được điều chỉnh bởi luật pháp của Cộng hòa Nhân dân Trung Hoa. Nếu bất kỳ điều khoản nào của thỏa thuận này không hợp lệ hoặc không thể thi hành do luật pháp của Cộng hòa Nhân dân Trung Hoa bị tẩy chay, thì những điều khoản này sẽ có hiệu lực và sẽ được phân tích lại để sát với mục đích ban đầu của thỏa thuận này và các quy định khác của điều này thỏa thuận sẽ vẫn có đầy đủ hiệu lực.</p>
      <p class="con">2. Nếu bạn có bất kỳ tranh chấp nào với công ty do thỏa thuận này, hai bên sẽ cố gắng giải quyết thông qua thương lượng hữu nghị, nếu thương lượng không thành công, bạn đồng ý gửi tranh chấp liên quan đến tòa án nhân dân nơi đạt được thỏa thuận này để khởi kiện.</p>
      <p class="con">3. Để cung cấp cho bạn các dịch vụ tốt hơn hoặc các luật, quy định và điều chỉnh chính sách của quốc gia, "K188 Media" và các dịch vụ liên quan sẽ được cập nhật và thay đổi theo thời gian. một phần của thỏa thuận này. Sau đó, chúng tôi sẽ phát hành phiên bản cập nhật trong "K188 Media" và nhắc nhở bạn về nội dung cập nhật thông qua thông báo trên trang web chính thức (www.K188.vip) hoặc các phương pháp thích hợp khác trước khi các điều khoản cập nhật có hiệu lực và ngăn bạn hiểu điều này Phiên bản mới nhất, bạn cũng có thể kiểm tra phiên bản mới nhất của các điều khoản thỏa thuận trên trang chủ của trang web hoặc trang cài đặt phần mềm. Nếu bạn tiếp tục sử dụng phần mềm "K188" và các dịch vụ liên quan, bạn đồng ý chấp nhận nội dung của thỏa thuận sửa đổi này.
Nếu bạn có bất kỳ phản đối nào đối với các điều khoản thỏa thuận đã sửa đổi, vui lòng ngừng đăng nhập hoặc sử dụng phần mềm "K188" và các dịch vụ liên quan ngay lập tức. Nếu bạn tiếp tục đăng nhập hoặc sử dụng phần mềm "K188" và các dịch vụ liên quan, bạn sẽ được coi là đã chấp thuận và chấp nhận các điều khoản sửa đổi của thỏa thuận.</p>
      <p class="con">4. Các tiêu đề trong thỏa thuận này hoàn toàn thuận tiện để đọc và thiết lập, và không ảnh hưởng đến ý nghĩa hoặc cách giải thích của bất kỳ điều khoản nào trong thỏa thuận này.</p>
      <p class="con">5. Cả bạn và công ty đều là các chủ thể độc lập. Trong mọi trường hợp, thỏa thuận này không cấu thành bất kỳ hình thức đảm bảo hoặc điều kiện rõ ràng hoặc ngụ ý nào của công ty đối với người dùng, cũng như không cấu thành mối quan hệ đại lý, đối tác, liên doanh hoặc việc làm giữa hai bên.</p>


    </div>
     <div v-if="$store.state.lanCode==2||$store.state.lanCode==5">
<p class="title">Welcome to use "K188" software and related services!</p>
<p class="con">"K188" software and related services refer to the services provided to you by the company through the legally owned and operated client applications marked with the name "K188 Media" and the website of "K188 Media Network" (www.52188.com). Products and services, including but not limited to core functions such as personalized recommendation, publishing information, interactive communication, search query, and other functions, are platforms for creation and communication. The agreement with the company regarding your registration, login, use (hereinafter collectively referred to as "use") "K188" software and related services.
</p>
      
<p class="con">In order to provide you with better services, please read and fully understand this agreement, especially the terms concerning the exemption or limitation of liability, the terms of rights license and information use, before you start to use the "K188" software and related services, and agree to open, and use of special individual service terms, applicable law and dispute resolution terms, etc. Among them, important content such as the clauses on exemption or limitation of liability will be reminded in bold form, and you should read them carefully. If you are under the age of 18, please read and fully understand this agreement accompanied by your legal guardian, and use the "K188" software and related services with the consent of your legal guardian.</p>
<p class="con">If you do not agree to this agreement, it will prevent us from providing you with complete products and services, and you can also choose to stop using it. If you choose to agree to or use the "K188" software and related services, you realize that you have fully understood this agreement and agree to accept this agreement and other agreements and rules related to the "K188" software and related services as a party to this agreement. (including but not limited to the Proprietary Policy).</p>

      <p class="title">"K188" software and related services</p>
      <p class="con">1.When you use the "K188" software and related services, you can obtain the "K188 Media" client application or visit the relevant website of K188 Media Network (www.52188.com) through pre-installation, third-party downloads authorized by the company, etc. If you did not obtain this software from the company or a third party authorized by the company, the company cannot guarantee that the unofficial version of "K188" software can be used normally, and the loss you suffer therefrom has nothing to do with the company.</p>
      <p class="con">2. The company may develop different application software versions for different terminal devices. You can obtain, download and install the appropriate version according to the actual device conditions. If you no longer use the "K188" software and related services, you can also uninstall the corresponding application software by yourself.</p>
      <p class="con">3. In order to better improve user experience and services, the company will provide updates or changes to "K188" software and related services from time to time (including but not limited to software modification, upgrade, function enhancement, development of new services, software replacement, etc.), In order to ensure the security of "K188" software and related services and improve user services, after part or all of the "K188" software and related services are updated, the company will use appropriate methods (including but not limited to system prompts, announcements, etc.) , site letter, etc.) to remind you that you have the right to choose to accept the updated version; if you choose not to update, some functions of the "K188" software and related services will be restricted or cannot be used normally.</p>
      <p class="con">4. Unless prior written authorization from the company is obtained, the "K188" software and related services may not be accessed or used in any form, including but not for catalog adaptation, reproduction, dissemination, vertical search, substitution or transaction authorization.</p>
      <p class="con">5. You understand that to use the "K188" software and related services, you need to prepare your own terminal equipment (such as computers, mobile phones, etc.) related to the software and related services. “ ” website means that you are using the “K188” software and related services. In order to fully realize the full functions of “K188 Media”, you may need to connect the terminal equipment to the Internet, and you understand that you will be responsible for the required expenses (such as traffic fees). , Internet access fees, etc.).</p>
      <p class="con">6. The company grants you a personal, non-transferable, non-exclusive and non-commercial legal right to use "K188" software and related services. All other rights not expressly authorized in this agreement are still reserved by the company, and you must obtain the written permission of the company before exercising these rights.</p>
      <p class="con">7. You can start using "K188" software and related services without registration, but some functions or services may be affected. At the same time, you also understand that in order to enable you to better use the "K188" software and related services, and to ensure the security of your account, certain functions and/or certain individual services (such as threading and commenting services, etc.) will require you to follow the According to the provisions of relevant national laws and regulations, it can only be used after providing real identity information, real-name registration and login.</p>

      <p class="title">About "Account"</p>
      <p class="con">1. "K188" software and related services provide you with a registration channel, you can choose a legal character combination as your account, and set a password that meets security requirements at the same time. Credentials for using "K188" software and related services.</p>
      <p class="con">2. You understand and promise that the account you set up shall not violate national laws and regulations and the relevant rules of the company, and shall not carry out any acts that infringe on national interests, damage the legitimate rights and interests of other citizens, or harm social morality. Your account name, avatar and The registration information such as profile and other personal information shall not contain illegal or bad information, and the so-called permission of others shall not be used in the name of others (including but not limited to falsely using other people's names, names, font sizes, avatars, etc.) Register a "K188 Media" account (including but not extending previous registration, batch registration of accounts, etc.). The company reserves the right to review the information you submit.</p>
      <p class="con">3. Your account is limited to your own use, which is called the written consent of the company. It is prohibited to give, borrow, rent, transfer, sell or otherwise allow others to use the account in any form. It is not the initial registrant of the account. In order to protect the security of the account, the company has the right to immediately suspend or terminate the provision of services to the registered account, or replace the account.</p>
      <p class="con">4. You are responsible for maintaining the security and confidentiality of your personal account and password. Once you take full legal responsibility for the activities of the army in the name of the registered account, including but not limited to any activities you perform on the "K188" software and related services All legal liabilities that may arise from operational behaviors such as data modification, comment publishing, budget payment, etc. You immediately notify the Company of any breach of your account or any other security breach.</p>
      <p class="con">5. When you lose your account number or forget your password, you can follow the company's method to correct and request to retrieve your account number or password in a timely manner. You understand and agree that the company's password recovery mechanism only needs to identify the information filled in and system records. Special attention should be paid to your account and password. When you are finished using it, you should exit safely. You will be responsible for the fatal account theft or loss of password due to your own reasons such as improper storage or other force majeure factors.</p>
      <p class="con">6. When registering, using and managing an account, you should ensure the authenticity of the identity information filled in when registering an account. Please use true, correct, legal and valid relevant identification materials and necessary information when registering and managing your account ( In accordance with the relevant national laws and regulations, in order to use some functions of the "K188" software and related services, you need to fill in the real identity information, please follow the relevant instructions. Complete the real-name authentication as required by law, and pay attention to update the above-mentioned relevant information in time. Information. If the materials you submit or the information you provide is not standardized or does not meet the requirements, the company has the right to refuse to provide you with relevant functions, and you may not be able to use the "K188" software and related services or use them.</p>
      <p class="con">7. In addition to self-registered "K188 Media" account, users can also authorize the use of other software user accounts legally owned by them, including but not entered into the company and/or affiliated companies, as well as real-name registered third-party software user accounts to log in and use "K188" software. and related services, unless restricted or prohibited by third-party software or platforms. When the user logs in with the previous account, he should ensure that the corresponding account has been registered with the real name, and the relevant terms of this agreement shall be applied at the same time.</p>
      <p class="con">8. You understand and agree that in addition to your login and use of "K188" software and related services, you can also use your "K188 Media" account to log in and use other software and services provided by the company and its affiliates. When you log in with the "K188 Media" account and use the continued service, you will be bound by the "User Agreement" and other terms of the agreement of the actual provider of the duplicate service.</p>
      <p class="con">9. In order to improve the exposure and publishing efficiency of your content, you agree that your account on this software/website and all content published by the corresponding account authorize the company to automatically and synchronously publish it to the company and/or affiliates for operation with your account. other software and websites. Your operations of publishing, modifying, and deleting content on this software/website will be synchronized to the above-mentioned series of other software and websites. Other software products and websites (if any) operated by the company shall abide by the terms of the User Agreement and other agreements of the software and the website itself.</p>
      <p class="con">10. After you complete the account registration of "K188 Media", log in and perform reasonable and necessary authentication, you can browse and modify the personally identifiable information submitted by yourself at any time. You understand and agree that you may not be able to modify the initial registration information and other verification information provided during registration for reasons of security and identification (such as account or password recovery and recovery services, etc.). You can also apply for an account number. The company will assist you to delete your account under reasonable circumstances such as personal identity, security status, device information, etc. and after necessary verification, and delete all information about your account according to your requirements. Except as provided.</p>
      <p class="con">11. You understand and agree that in order to make full use of account resources, the company has the right to delete your account if you fail to log in for the first time after registration or fail to log in to use your account for more than two consecutive months.</p>
      

      <p class="title">User Personal Information Protection</p>
      <p class="con">The company works with you to protect your personal information (that is, the information that can identify the user independently or in combination with other information). Protecting the user's personal information is one of the company's basic principles. In the process of using "K188" software and related services, you may need to provide your personal information (including but not limited to name, phone number, location information, etc.), and Brake Company will provide you with better services and corresponding technical support . The company will use encryption technology, anonymization processing and other technical measures that match the "K188" software and related services and other security measures to protect your personal information.</p>

      <p class="title">User Code of Conduct</p>
      <p class="con">1. User behavior requires you to be correctly responsible for your use of the software and related services. Unless permitted by law or with the prior written permission of the company, you shall not use the “K188” software and related services in the following behaviors:</p>
      <p class="con">1.1 Use any plug-ins, plug-ins, systems or third-party tools authorized or licensed by the company to interfere, destroy, modify or exert other influences on the normal operation of "K188" software and related services.</p>
      <p class="con">1.2 Use or conduct any behaviors that endanger computer network security by using or targeting "K188" software and related services, including but not limited to:</p>
      <p class="con">(1) illegally infringing on other people's networks, interfering with the normal functions of other people's networks, stealing network data and other activities that endanger network security;</p>
      <p class="con">(2) Provide programs and tools specially used for military intrusive networks, interfering with normal network functions and protective measures, stealing network data and other activities that endanger network security;</p>
      <p class="con">(3) Provide technical support, advertising promotion, payment settlement and other assistance for those who are aware of the activities of the civilian army that endanger network security;</p>
      <p class="con">(4) Use the data permitted by the permission or the server/account permitted by the access permission;</p>
      <p class="con">(5) Allow access to public computer networks or other computer systems and delete, modify, and add stored information;</p>
      <p class="con">(6) Permit, attempt to probe, scan, test the weaknesses of the "K188 Media" system or network or other conduct that undermines network security;</p>
      <p class="con">(7) Attempting to interfere, destroying the normal operation of the "K188 Media" system or website, maliciously spreading programs or viruses, and other behaviors that disrupt and interfere with normal network information services;</p>
      <p class="con">(8) Forge TCP/IP packet names or partial names;</p>
      <p class="con">(9) Reverse engineering, disassembling, compiling or otherwise trying to discover the source code of this software for the "K188" software and related services;</p>
      <p class="con">(10) Maliciously registering accounts of "K188" software and related services, including but not extending duplicates, and registering accounts in batches;</p>
      <p class="con">(11) Violation of laws and regulations, this agreement, relevant rules of the company and other acts that violate the legitimate rights and interests of others.</p>
      <p class="con">1.3 If the company has reason to believe that your behavior violates or may violate the above agreement, the company can independently judge and deal with it, and has the right to terminate the provision of services to you without prior notice, and pursue relevant legal responsibilities.</p>
      <p class="con">2. Information content specification</p>
      <p class="con">2.1 After you complete the real-name authentication as required, you can log in to “K188 Media” with your registered account or your “K188 Media” partner platform account to publish content, post comments, etc.</p>
      <p class="con">2.2 The company is committed to making publishing information and posting comments a civilized, rational, friendly, and alternative exchange of opinions. While promoting the development of information publishing, interactive communication, and commenting on posts, we will continue to strengthen the corresponding information security management capabilities, improve information publishing, self-discipline in posting comments, earnestly fulfill social responsibilities, abide by national laws and regulations, respect the legitimate rights and interests of citizens, and respect the legitimate rights and interests of citizens. Social order and good customs.</p>
      <p class="con">2.3 Your comments, publications, and dissemination of content should consciously abide by the constitution, regulations, public order, respect for social morality, socialist system, national interests, legitimate rights and interests of citizens, morality and authenticity of information. Make, reproduce, publish, and disseminate the following information content prohibited by laws and regulations:</p>
      <p class="con">(1) Opposition to the basic principles established by the Constitution;</p>
      <p class="con">(2) Endangering national security and surpassing state secrets;</p>
      <p class="con">(3) Subversion of state power, overthrow of the socialist system, incitement to split the country, and destruction of national unity;</p>
      <p class="con">(4) Damage to national honor and interests;</p>
      <p class="con">(5) Advocating terrorism and extremism;</p>
      <p class="con">(6) Advocating ethnic hatred, ethnic discrimination, or undermining ethnic unity;</p>
      <p class="con">(7) Inciting regional discrimination or regional hatred;</p>
      <p class="con">(8) Undermining the national religious policy and promoting cults and superstitions;</p>
      <p class="con">(9) Fabricating or spreading rumors and false information, disrupting economic and social order, and undermining social stability;</p>
      <p class="con">(10) Spreading, disseminating violence, obscenity, pornography, fraud, murder, terror or instigating crimes;</p>
      <p class="con">(11) Violating the lawful rights and interests of minors or harming the human health of minors;</p>
      <p class="con">(12) Secretly photographing or secretly recording others without the permission of the owner, and infringing upon the legal rights of others;</p>
      <p class="con">(13) Content that contains horror, violence, blood, high risk, and endangers the performer's own or others' physical health;</p>
      <p class="con">(14) Endangering network security, using the network army to endanger national security, honor and interests;</p>
      <p class="con">(15) Insulting or blaspheming others, infringing upon the legitimate rights and interests of others;</p>
      <p class="con">(16) Violently intimidating, threatening, or conducting human flesh searches against others;</p>
      <p class="con">(17) Involving civilian privacy, personal information or materials;</p>
      <p class="con">(18) Spreading foul language and damaging social order and good customs;</p>
      <p class="con">(19) Content that infringes upon the exclusive rights, reputation rights, portrait rights, intellectual property rights and other legitimate rights and interests of others;</p>
      <p class="con">(20) Spreading commercial advertisements, or similar commercial solicitation information, excessive marketing information and spam information;</p>
      <p class="con">(21) Comments in languages ​​other than those commonly used on this website;</p>
      <p class="con">(22) has nothing to do with the information reviewed;</p>
      <p class="con">(23) The information published is meaningless, or the combination of characters is deliberately used to evade technical review;</p>
      <p class="con">(24) Other information that violates laws and regulations, policies and public order and good customs, interferes with the normal operation of "K188 Media" or violates the legitimate rights and interests of other users or third parties.</p>
      <p class="con">3. The company has set up a public complaint and reporting platform. You can complain to the company according to the company's public complaint and reporting system, and report classified violations of laws and regulations, illegal communication activities, illegal and harmful information, etc. The company will promptly prosecute and handle your complaints and reports. , in order to jointly create a clean and upright cyberspace.</p>

      <p class="title">Specifications for the use of information content of "K188 Media"</p>
      <p class="con">1. Without the written permission of the company, you shall not provide or assist any third party to perform the following acts on the information content in the "K188" software and related services of this agreement by yourself or authorization:</p>
      <p class="con">(1) Copy, read, and use the information content of "K188" software and related services, including but not limited to publicity, increasing reading, browsing and other commercial purposes;</p>
      <p class="con">(2) Editing, sorting, and arranging the information content of "K188" software and related services without authorization, and then displaying it on channels other than the source page of "K188" software and related services;</p>
      <p class="con">(3) Use any form of identification method including but not pre-determined special logos, special codes, etc., to generate traffic, read volume guidance, transfer, hijacking, etc. to the information content of the "K188" software and related services by itself or assist a third party. Influence;</p>
      <p class="con">(4) Other acts of illegally obtaining or using the information content of "K188" software and related services.</p>
      <p class="con">2. With the written permission of the company, your sharing and forwarding of the information content of the "K188" software and related services should also comply with the following specifications:</p>
      <p class="con">(1) For relevant data such as crawling, statistic, and obtained related search hot words, hit rate, classification, search volume, click rate, reading volume, etc., the company agrees in advance in writing, and shall not publicize or provide the above data in any way, to any third person;</p>
      <p class="con">(2) Any placement in any form on the source webpage of the "K188" software and related services, including but not limited to the homepage (configuration file page) links of the "K188" software and related services, links to the advertising system, etc. Block, insert, pop-up windows, etc. in any form on the display of the source page of the "K188" software and related services;</p>
      <p class="con">(3) Take appropriate safe, effective and strict measures to prevent the information content of "K188" software and related services from being illegally obtained by third parties in any form including but not limited to "spider" programs;</p>
      <p class="con">(4) The relevant data content shall not be used for purposes beyond the scope of the company's written permission, for any form of sales and commercial use, or to engage with, provide or allow third parties to use in any way;</p>
      <p class="con">(5) The behavior of sharing, forwarding, and copying the information content of "K188" software and related services to any third party shall comply with other norms and standards formulated by the company.</p>

      <p class="title">Breach of contract</p>
      <p class="con">1. In response to your violation of this agreement or other terms of service, the company has the right to independently judge and take advance warning according to the situation, refuse to publish, immediately stop the transmission of information, delete the thread, prohibit short-term replacement, restrict some or all functions of the account until permanent Relevant records will be kept for relevant suspects who violate laws and regulations and are suspected of illegal crimes, and will be reported to the relevant competent authorities in accordance with the law, and will cooperate with the relevant competent authorities in their investigations.</p>
      <p class="con">2. If you violate the provisions of this agreement or other terms of service and cause a third-party complaint or lawsuit, you should handle it yourself and assume all possible legal responsibilities. If the company and its affiliates make compensation to any third party or comply with state organs due to your illegal, breach or breach of contract, you should also fully compensate the company and its affiliates for all losses suffered as a result.</p>
      <p class="con">3. The company respects and protects the intellectual property rights, reputation rights, name rights, ownership rights and other legitimate rights and interests of users and others. You guarantee that the text, pictures, video, audio, links, etc. uploaded when using the "K188" software and related services do not infringe any third party's intellectual property rights, reputation rights, name rights, ownership rights and other rights and legitimate rights and interests. Otherwise, the company reserves the right to remove the allegedly infringing content upon notification from the rights owner or related parties. For all claims made by third parties, you shall handle and bear all legal responsibilities that may result; if the company and its affiliates suffer losses (including economic, goodwill, etc. losses) due to your ownership behavior, you shall also The Company and its affiliates shall be fully compensated for all losses complied with.</p>

      <p class="title">CHANGES, INTERRUPTIONS AND TERMINATION OF SERVICES</p>
      <p class="con">1. You understand and agree that the "K188" software and related services provided by the company are provided in accordance with the status quo that the existing technology and conditions can achieve. The company will do its best to provide you with services to ensure the continuity and security of services. You understand that the company cannot foresee and prevent technical and other risks at any time, including but not gradually force majeure, network reasons, third-party service defects, third-party websites and other reasons that may result in service interruption, inability to use the software and services normally, and other losses and risk.</p>
      <p class="con">2. You understand and agree that the company has the right to decide the service/function settings, scope, modification, interruption, suspension or termination of the "K188" software and related services according to the specific circumstances for the needs of the overall operation of the service and the safety of the platform operation.</p>
      

      <p class="title">advertise</p>
      <p class="con">1. You understand and agree that in the process of using "K188" software and related services, the company may promote relevant information, advertising or brand promotion services to you, and the company will display in "K188" software and related services Commercial advertisements, promotions or information (including commercial or non-commercial information) related to "K188" software and related services and/or third-party suppliers, partners.</p>
      <p class="con">2. When using "K188 Media", the company will push programmatic advertisements to you based on priorities, interests, etc. You can turn off the push of programmatic advertisements in the "K188 Media" settings. If it is turned off, the number of advertisements you see will remain the same, but the ad will be less relevant.</p>
      <p class="con">3. In accordance with the company's advertising and promotion related obligations stipulated by law, you must determine the authenticity and reliability of the advertisement or promotion information by yourself and be responsible for your own judgment. Except as provided by laws and regulations, you shall be solely responsible for any damages or losses caused by your purchases, transactions, or suspected content infringement due to the advertisement or promotional information, and the company shall not be liable.</p>
      

      <p class="title">intellectual property</p>
      <p class="con">1. The encryption of the content (including but not limited to software, technology, programs, web pages, text, pictures, images, audio, video, charts, layouts, electronic documents, etc.) provided by the company in the "K188" software and related services belongs to Company owned. The copyright, patent rights and other intellectual property rights of the software on which the company provides this service is owned by the company. Equipment monitoring, copying, dissemination, display, merging, uploading, downloading) content in the "K188" software and related services.
</p>
      <p class="con">2. You understand and agree that the text, pictures, videos, audios, etc. published and uploaded when using the "K188" software and related services are all original or authorized by you. The copyright of any content you upload and publish through "K188 Media" belongs to you or the original copyright owner.</p>
      <p class="con">3. You know, understand and agree that, in order to continuously improve and provide you with better services, the content (including but not limited to text, pictures, images, audios, etc.) that you upload, publish, transmit or disseminate through "K188" software and related services , video and/or audio in music, sound, dialogue, etc.), Licensing Company and its Affiliates, Controlling Company, inheriting Company's respective worldwide, free, non-exclusive, sublicensable (through multiple tiers) rights ( Including but not pre-reproduction rights, information network dissemination rights, adaptation rights, compilation rights, modification rights, translation rights, production derivatives, performance and display rights), the scope of use includes but is not limited to current or other websites, applications, products or terminal equipment, etc. You hereby acknowledge and agree that the grant of the above rights is included in the content, "K188 Media" / "K188 Media Network", any publicity, promotion, advertising and/or for the avoidance of doubt, about the company and/or the company brand, You agree that the authorization of the above rights includes the licensed use, reproduction, display, transmission of personal images, likenesses, names, trademarks, service marks, brands, names, logos, company marks and others that you own or are licensed to use and embed in the Content materials, materials, etc.</p>
      <p class="con">4. You confirm and agree to authorize the company to act in the company's own name or entrust a professional third party to arbitrate, mediate, reconcile, etc., the copyright infringement you upload and publish, and the company has the right to take decisions on rights protection and implement them independently.</p>
      <p class="con">5. The company provides technical support for the development and operation of "K188 Media", and converts all data and information generated during the development and operation of "K188" software and related services to all rights within the scope permitted by copyright laws and regulations.</p>
      <p class="con">6. Please do not use any internal information of the company including but not limited to "K188", "K188 Media", "K188 Media Account", "K188 Media Network" and "www.52188.com" under any circumstances. Company, with the prior written consent of the The behavior of handling these flags. You shall bear all legal responsibilities for the losses caused to the company or others due to your violation of this agreement by using the company's above-mentioned trademarks, logos, etc.</p>
      

      <p class="title">Disclaimer</p>
      <p class="con">1. You understand and agree that the "K188" software and related services may be affected or interfered by various factors, and the company does not guarantee (including but not limited to):</p>
      <p class="con">1.1 "K188" software and related services are fully suitable for all usage requirements of users;</p>
      <p class="con">1.2 The "K188" software and related services are uninterrupted, timely, safe, reliable or error-free; any software, services or other materials you obtain through the company meet the user's expectations;</p>
      <p class="con">1.3 Any errors in "K188" software and related services will be corrected.</p>
      <p class="con">2. If there is any online information, account password, advertisement or promotion and other information suspected of being suspected of borrowing or other suspected property, please treat it with caution and make your own judgment. You are therefore entitled to profit, business reputation, data loss or other tangible or intangible losses. The company shall not be liable for any direct, indirect, incidental, special, consequential or punitive damages.</p>
      <p class="con">3. You understand and agree that in the process of using "K188" software and related services, force majeure factors may be encountered (force majeure refers to unforeseeable, insurmountable and unavoidable objective events), including but not limited to natural disasters (such as floods, earthquakes, typhoons, etc.), government actions, wars, strikes, riots, riots, etc. In the event of force majeure, the company will try to repair it as soon as possible, but the company is exempt from liability within the scope of laws and regulations for losses caused by force majeure.</p>
      <p class="con">4. The company has the right to deal with illegal content according to this agreement. This right does not constitute an obligation or commitment of the company, and the company cannot guarantee timely detection of illegal acts or corresponding handling.
</p>
      <p class="con">5. You understand and agree that with regard to "K188" software and related services, the company does not provide any kind of express or implied warranties or conditions, including but not limited to commercial merchantability, suitability for specific purposes, etc. The use of and related services shall be at your own risk.</p>
      <p class="con">6. You understand and agree that this agreement is to comply with national laws and regulations, maintain public order and good customs, and protect the legitimate rights and interests of others. The company will do its best to make judgments in accordance with relevant laws and regulations within its capabilities, but it does not guarantee that the company's judgment is completely consistent with judicial organs. , the judgment of the administrative agency is consistent, and you have understood and agreed to bear the consequences arising therefrom.</p>
      <p class="con">7. Under no circumstances shall the company be liable for any indirect, consequential, punitive, incidental, special or punitive damages, including loss of profits suffered by you due to your use of the "K188" software and related services. The entire responsibility of the company to you, regardless of the reason or nominal behavior, will never exceed the fees (if any) you pay to the company for using the "K188" software and related services within the member.</p>


      <p class="title">Special agreement on single service and third-party service</p>
      <p class="con">1. "K188" software and related services include links to the company's acquisition of its information or information content in various legal ways, as well as other single services legally operated by the company and/or its affiliates. You can open and use the above individual services in the "K188" software. Certain individual services may require you to also accept an agreement or other rules governing this particular arrangement between you and the individual service provider, and if necessary, provide you with these agreements in a conspicuous manner for the one-way service you plan to use , the rules, for your reference and consent. Once you start to use the above-mentioned services, you are deemed to have understood and accepted the relevant agreements and rules for a single service. If the period of use is not indicated, or the period of use is not indicated as "permanent", "indefinite" or "unlimited", the period of use of these products or services is from the time the user starts using the product or service until the product or service is in Until the date of offline in the "K188" software.</p>
      <p class="con">2. If you use software or related services provided by a third party in the "K188" software, in addition to complying with this agreement and the relevant rules of K188 media, you may also need to agree to and abide by the third party's agreement, proprietary policy and related rules. Disputes, losses or damages arising from third-party software and related services shall be resolved by you and the third party, and the company shall not be liable to you or any third party for this.</p>
      

      <p class="title">Terms of Use for Minors</p>
      <p class="con">1. If the user is a minor under the age of 18, the "K188" software and related services should only be used after carefully reading this agreement under the guardian's supervision, guidance and obtaining the guardian's consent.</p>
      <p class="con">2. The company's protection of minors' personal information. When minor users fill in personal information, please strengthen their awareness of personal protection and take appropriate measures, and correctly use the "K188" software and related services under the guidance of their guardians.</p>
      <p class="con">3. Minor users understand that if you violate the laws and regulations and the content of this agreement, you and your guardian should bear all legal responsibilities that may arise in accordance with the laws and regulations.</p>
      <p class="con">4. Special reminder for minor users:</p>
      <p class="con">4.1 Teenagers who use this software and related services should learn to use the Internet correctly within a reasonable range under the supervision and guidance of their guardians, avoid indulging in virtual cyberspace, and develop good Internet habits.</p>
      <p class="con">4.2 Young users must abide by the "National Youth Network Civilization Convention":
</p>
      <p class="con">(1) Be good at online learning and do not browse bad information;</p>
      <p class="con">(2) To communicate honestly and friendly, do not insult or deceive others;</p>
      <p class="con">(3) To enhance self-protection awareness, do not date netizens at will;</p>
      <p class="con">(4) To maintain network security and not damage the network level;</p>
      <p class="con">(5) To be beneficial to physical and mental health, and not to indulge in virtual time and space.</p>
      <p class="con">5. In order to better protect the rights of minors, the company reminds users to publish content containing minors’ material carefully. Once released, it is deemed that the user agrees to the software and related services to display information, portraits, voices, etc. of minors. And allow the company to use and process these content related to minors in accordance with this agreement.</p>
      

      <p class="title">other</p>
      <p class="con">1. The establishment, entry into force, conclusion, interpretation and dispute resolution of this agreement shall be governed by the laws of the People's Republic of China. If any of the provisions of this agreement are invalid or unenforceable due to the legal boycott of the People's Republic of China, these provisions will be re-analyzed in accordance with the meaning of the original provisions of this agreement, and other provisions of this agreement shall still have full force and effect .</p>
      <p class="con">2. If you have any dispute with the company due to this agreement, both parties should try to resolve it through friendly negotiation; if the negotiation fails, you agree to submit the relevant dispute to the people's court where this agreement is reached for settlement.</p>
      <p class="con">3. In order to provide you with better services or national laws and regulations, policy adjustments, "K188 Media" and related services will be updated and changed from time to time, and we will revise this agreement in due course, and these revisions form part of this agreement. After that, we will release the updated version on "K188 Media", and remind you of the updated content through the official website (www.52188.com) announcement or other appropriate means before the updated terms take effect, so that you can keep abreast of the terms of this agreement. The latest version, you can also check the terms of the latest version of the agreement on the website homepage or software settings page. If you continue to use the "K188" software and related services, you agree to accept the revised content of this agreement.If you have any objection to the revised terms of the agreement, please stop logging in or using the "K188" software and related services immediately. If you continue to log in or use the "K188" software and related services, it is deemed that you acknowledge and accept the revised terms of the agreement.</p>
      <p class="con">4. The headings in this agreement are designed for complete convenience and reading, and do not affect the meaning or interpretation of any provision in this agreement.</p>
      <p class="con">5. You and the company are independent subjects, and this agreement does not constitute any form of express or implied guarantee or condition of the company to the user under any circumstances, nor does it constitute an agency, partnership, joint venture or employment relationship between the two parties.</p>
    </div>
    </div>

</template>
<script>
export default {
  name: 'ruleClause',
}
</script>

<style scoped lang="less">
.ruleClause{
  padding: 45px 40px;
  .title{
    font-size: 16px;
    color: #1486ff;
    padding-bottom: 5px;
    padding-top: 35px;
  }
  .title:first-child{
      padding-top: 0px;
  }
  .con{
    font-size: 14px;
    color: #71819d;
    line-height: 34px;
    span{
      color: #1486ff;
    }
  }
  .pic{
      overflow: hidden;
      padding-top: 10px;
      img{
          width: 780px;
      }
  }
}
</style>